import { defineConfig } from 'astro/config';

// Static output. Deployed to GitHub Pages by .github/workflows/deploy.yml.
// Sitemap is generated by src/pages/sitemap.xml.ts from the same data the
// pages are built from, so it cannot drift out of sync with real routes.
export default defineConfig({
  site: 'https://anysize.shop',
  output: 'static',
  build: { format: 'directory' },
  compressHTML: true,
});
