import { defineConfig } from 'astro/config';

// Static output. Vercel auto-detects Astro and serves dist/ with zero config.
// Sitemap is generated by src/pages/sitemap.xml.ts from the same data the
// pages are built from, so it cannot drift out of sync with real routes.
export default defineConfig({
  site: 'https://marshallsheds.com',
  output: 'static',
  build: { format: 'directory' },
  compressHTML: true,
});
